<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.jiejie</groupId>
        <artifactId>jiejie-admin</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>jiejie-core</artifactId>
    <packaging>pom</packaging>
    <name>Jiejie Core</name>
    <description>业务核心层 - 业务模块</description>

    <modules>
        <module>jiejie-system</module>
        <module>jiejie-file</module>
        <module>jiejie-gen</module>
        <module>jiejie-message</module>
        <module>jiejie-auth</module>
        <module>jiejie-biz</module>
        <module>jiejie-workflow</module>
    </modules>
</project>
